-- Add migration script here
CREATE TABLE halo3.service_record (
  player_xuid BIGINT NOT NULL PRIMARY KEY,
  player_name VARCHAR(16) NOT NULL,
  appearance_flags SMALLINT NOT NULL,
  primary_color SMALLINT NOT NULL,
  secondary_color SMALLINT NOT NULL,
  tertiary_color SMALLINT NOT NULL,
  is_elite SMALLINT NOT NULL,
  foreground_emblem SMALLINT NOT NULL,
  background_emblem SMALLINT NOT NULL,
  emblem_flags SMALLINT NOT NULL,
  emblem_primary_color SMALLINT NOT NULL,
  emblem_secondary_color SMALLINT NOT NULL,
  emblem_background_color SMALLINT NOT NULL,
  spartan_helmet SMALLINT NOT NULL,
  spartan_left_shoulder SMALLINT NOT NULL,
  spartan_right_shoulder SMALLINT NOT NULL,
  spartan_body SMALLINT NOT NULL,
  elite_helmet SMALLINT NOT NULL,
  elite_left_shoulder SMALLINT NOT NULL,
  elite_right_shoulder SMALLINT NOT NULL,
  elite_body SMALLINT NOT NULL,
  service_tag VARCHAR(5) NOT NULL,
  campaign_progress INTEGER NOT NULL,
  highest_skill INTEGER NOT NULL,
  total_exp INTEGER NOT NULL,
  unknown_insignia INTEGER NOT NULL,
  rank INTEGER NOT NULL,
  grade INTEGER NOT NULL,
  unknown_insignia2 INTEGER NOT NULL,
  first_played TIMESTAMP NOT NULL,
  last_played TIMESTAMP NOT NULL,
  bungienet_user_flags BIGINT NOT NULL,
  is_silver_or_gold_live BOOLEAN NOT NULL,
  is_online_enabled BOOLEAN NOT NULL,
  gamer_region INT NOT NULL,
  cheat_flags BIGINT NOT NULL,
  ban_flags BIGINT NOT NULL,
  matchmade_ranked_games_played BIGINT NOT NULL,
  matchmade_ranked_games_completed BIGINT NOT NULL,
  matchmade_ranked_games_won BIGINT NOT NULL,
  matchmade_unranked_games_played BIGINT NOT NULL,
  matchmade_unranked_games_completed BIGINT NOT NULL,
  custom_games_completed BIGINT NOT NULL
);

CREATE INDEX idx_player_name ON halo3.service_record (player_name);

insert into halo3.service_record (
    player_xuid,
    player_name,
    appearance_flags,
    primary_color,
    secondary_color,
    tertiary_color,
    is_elite,
    foreground_emblem,
    background_emblem,
    emblem_flags,
    emblem_primary_color,
    emblem_secondary_color,
    emblem_background_color,
    spartan_helmet,
    spartan_left_shoulder,
    spartan_right_shoulder,
    spartan_body,
    elite_helmet,
    elite_left_shoulder,
    elite_right_shoulder,
    elite_body,
    service_tag,
    campaign_progress,
    highest_skill,
    total_exp,
    unknown_insignia,
    "rank",
    grade,
    unknown_insignia2,
    first_played,
    last_played,
    bungienet_user_flags,
    is_silver_or_gold_live,
    is_online_enabled,
    gamer_region,
    cheat_flags,
    ban_flags,
    matchmade_ranked_games_played,
    matchmade_ranked_games_won,
    matchmade_ranked_games_completed,
    matchmade_unranked_games_played,
    matchmade_unranked_games_completed,
    custom_games_completed
)
select 	player_xuid,
          player_name,
          appearance_flags,
          primary_color,
          secondary_color,
          tertiary_color,
          player_model_choice,
          foreground_emblem,
          background_emblem,
          emblem_flags,
          emblem_primary_color,
          emblem_secondary_color,
          emblem_background_color,
          spartan_model_area_0,
          spartan_model_area_1,
          spartan_model_area_2,
          spartan_model_area_3,
          elite_model_area_0,
          elite_model_area_1,
          elite_model_area_2,
          elite_model_area_3,
          service_tag,
          campaign_difficulty_completed,
          global_statistics_highest_skill,
          host_stats_global_experience,
          0 unknown_insignia,
          host_stats_global_rank,
          host_stats_global_grade,
          0 as unknown_insignia2,
          first_played,
          last_played,
          bungienet_user_flags,
          is_silver_or_gold_live,
          is_online_enabled,
          gamer_region,
          cheat_flags,
          ban_flags,
          matchmade_ranked_games_played,
          matchmade_ranked_games_won,
          matchmade_ranked_games_completed,
          matchmade_unranked_games_played,
          matchmade_unranked_games_completed,
          custom_games_completed
from (
     WITH latest_reports AS (
        SELECT DISTINCT ON (p.player_xuid)
            p.player_xuid,
	        p.player_name,
	        p.carnage_report_id AS latest_carnage_report
        FROM halo3.carnage_report_player p
        JOIN halo3.carnage_report c ON p.carnage_report_id = c.id
        where p.player_xuid != 0 and (p.player_xuid & 54043195528445952) = 0
        ORDER BY p.player_xuid desc
    )
    SELECT crp.*
    FROM latest_reports lr
    JOIN halo3.carnage_report_player crp ON lr.latest_carnage_report = crp.carnage_report_id and lr.player_xuid = crp.player_xuid
    ORDER BY lr.player_xuid DESC
) crp;


CREATE OR REPLACE PROCEDURE halo3.upsert_service_records_from_multiplayer_match(IN submitted_report_id uuid)
 LANGUAGE plpgsql
AS $procedure$
BEGIN
    -- Upsert service records based on the carnage_report_id filter
INSERT INTO halo3.service_record (
    player_xuid,
    player_name,
    appearance_flags,
    primary_color,
    secondary_color,
    tertiary_color,
    is_elite,
    foreground_emblem,
    background_emblem,
    emblem_flags,
    emblem_primary_color,
    emblem_secondary_color,
    emblem_background_color,
    spartan_helmet,
    spartan_left_shoulder,
    spartan_right_shoulder,
    spartan_body,
    elite_helmet,
    elite_left_shoulder,
    elite_right_shoulder,
    elite_body,
    service_tag,
    campaign_progress,
    highest_skill,
    total_exp,
    unknown_insignia,
    "rank",
    grade,
    unknown_insignia2,
    first_played,
    last_played,
    bungienet_user_flags,
    is_silver_or_gold_live,
    is_online_enabled,
    gamer_region,
    cheat_flags,
    ban_flags,
    matchmade_ranked_games_played,
    matchmade_ranked_games_won,
    matchmade_ranked_games_completed,
    matchmade_unranked_games_played,
    matchmade_unranked_games_completed,
    custom_games_completed
)
SELECT
    crp.player_xuid,
    crp.player_name,
    crp.appearance_flags,
    crp.primary_color,
    crp.secondary_color,
    crp.tertiary_color,
    crp.player_model_choice,
    crp.foreground_emblem,
    crp.background_emblem,
    crp.emblem_flags,
    crp.emblem_primary_color,
    crp.emblem_secondary_color,
    crp.emblem_background_color,
    crp.spartan_model_area_0,
    crp.spartan_model_area_1,
    crp.spartan_model_area_2,
    crp.spartan_model_area_3,
    crp.elite_model_area_0,
    crp.elite_model_area_1,
    crp.elite_model_area_2,
    crp.elite_model_area_3,
    crp.service_tag,
    crp.campaign_difficulty_completed,
    crp.global_statistics_highest_skill,
    crp.host_stats_global_experience,
    0 AS unknown_insignia,
    crp.host_stats_global_rank,
    crp.host_stats_global_grade,
    0 AS unknown_insignia2,
    crp.first_played,
    crp.last_played,
    crp.bungienet_user_flags,
    crp.is_silver_or_gold_live,
    crp.is_online_enabled,
    crp.gamer_region,
    crp.cheat_flags,
    crp.ban_flags,
    crp.matchmade_ranked_games_played,
    crp.matchmade_ranked_games_won,
    crp.matchmade_ranked_games_completed,
    crp.matchmade_unranked_games_played,
    crp.matchmade_unranked_games_completed,
    crp.custom_games_completed
FROM halo3.carnage_report_player crp
WHERE crp.carnage_report_id = submitted_report_id
  AND crp.player_xuid != 0
      AND (crp.player_xuid & 54043195528445952) = 0
ON CONFLICT (player_xuid)
    DO UPDATE
           SET player_name = EXCLUDED.player_name,
           appearance_flags = EXCLUDED.appearance_flags,
           primary_color = EXCLUDED.primary_color,
           secondary_color = EXCLUDED.secondary_color,
           tertiary_color = EXCLUDED.tertiary_color,
           is_elite = EXCLUDED.is_elite,
           foreground_emblem = EXCLUDED.foreground_emblem,
           background_emblem = EXCLUDED.background_emblem,
           emblem_flags = EXCLUDED.emblem_flags,
           emblem_primary_color = EXCLUDED.emblem_primary_color,
           emblem_secondary_color = EXCLUDED.emblem_secondary_color,
           emblem_background_color = EXCLUDED.emblem_background_color,
           spartan_helmet = EXCLUDED.spartan_helmet,
           spartan_left_shoulder = EXCLUDED.spartan_left_shoulder,
           spartan_right_shoulder = EXCLUDED.spartan_right_shoulder,
           spartan_body = EXCLUDED.spartan_body,
           elite_helmet = EXCLUDED.elite_helmet,
           elite_left_shoulder = EXCLUDED.elite_left_shoulder,
           elite_right_shoulder = EXCLUDED.elite_right_shoulder,
           elite_body = EXCLUDED.elite_body,
           service_tag = EXCLUDED.service_tag,
           campaign_progress = EXCLUDED.campaign_progress,
           highest_skill = EXCLUDED.highest_skill,
           total_exp = EXCLUDED.total_exp,
           unknown_insignia = EXCLUDED.unknown_insignia,
           "rank" = EXCLUDED."rank",
           grade = EXCLUDED.grade,
           unknown_insignia2 = EXCLUDED.unknown_insignia2,
           first_played = EXCLUDED.first_played,
           last_played = EXCLUDED.last_played,
           bungienet_user_flags = EXCLUDED.bungienet_user_flags,
           is_silver_or_gold_live = EXCLUDED.is_silver_or_gold_live,
           is_online_enabled = EXCLUDED.is_online_enabled,
           gamer_region = EXCLUDED.gamer_region,
           cheat_flags = EXCLUDED.cheat_flags,
           ban_flags = EXCLUDED.ban_flags,
           matchmade_ranked_games_played = EXCLUDED.matchmade_ranked_games_played,
           matchmade_ranked_games_won = EXCLUDED.matchmade_ranked_games_won,
           matchmade_ranked_games_completed = EXCLUDED.matchmade_ranked_games_completed,
           matchmade_unranked_games_played = EXCLUDED.matchmade_unranked_games_played,
           matchmade_unranked_games_completed = EXCLUDED.matchmade_unranked_games_completed,
           custom_games_completed = EXCLUDED.custom_games_completed;
END;
$procedure$
;
