-- Add migration script here
CREATE TABLE halo3.matchmaking_quality (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    aborted BOOLEAN NOT NULL,
    assemble_timed_out BOOLEAN NOT NULL,
    left_assemble BOOLEAN NOT NULL,
    left_arbitration BOOLEAN NOT NULL,
    not_enough_hosts BOOLEAN NOT NULL,
    left_host_selection BOOLEAN NOT NULL,
    left_prepare_map BOOLEAN NOT NULL,
    vetoed BOOLEAN NOT NULL,
    map_id INTEGER NOT NULL,
    game_variant_name TEXT NOT NULL,
    game_variant_hash BYTEA NOT NULL,
    map_variant_name TEXT NOT NULL,
    map_variant_hash BYTEA NOT null,
    hit_arbitration_establis_and_connect_give_up BOOLEAN NOT NULL,
    hit_arbitration_completion_give_up BOOLEAN NOT NULL,
    searching BOOLEAN NOT NULL,
    gathering BOOLEAN NOT NULL,
    gathering_by_force BOOLEAN NOT NULL,
    ping_msec INTEGER NOT NULL,
    search_time INTEGER NOT NULL,
    gather_time INTEGER NOT NULL,
    arbitration_time INTEGER NOT NULL,
    host_selection_time INTEGER NOT NULL,
    prepare_map_time INTEGER NOT NULL,
    in_match_time INTEGER NOT NULL,
    qos_sample_count INTEGER NOT NULL,
    session_search_count INTEGER NOT NULL,
    live_service_qos_result_valid BOOLEAN NOT NULL,
    live_service_qos_result_probes_sent INTEGER NOT NULL,
    live_service_qos_result_probes_received INTEGER NOT NULL,
    live_service_qos_result_ping_msec_minimum INTEGER NOT NULL,
    live_service_qos_result_ping_msec_median INTEGER NOT NULL,
    live_service_qos_result_bandwidth_upstream_bps INTEGER NOT NULL,
    live_service_qos_result_bandwidth_downstream_bps INTEGER NOT NULL,
    live_service_qos_result_data_block_size INTEGER NOT NULL,
    live_service_qos_result_data_block INTEGER NOT NULL,
    nat_type_valid BOOLEAN NOT NULL,
    nat_type TEXT NOT NULL,
    primary_map_load_failure BOOLEAN NOT NULL,
    secondary_map_load_failure BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    inaddr TEXT NOT NULL,
    inaddr_online TEXT NOT NULL,
    port_online INTEGER NOT NULL,
    ab_online BYTEA NOT NULL
);

CREATE TABLE halo3.matchmaking_session_search (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    matchmaking_quality_id UUID NOT NULL,
    session_count INTEGER NOT NULL,
    start_timestamp INTEGER NOT NULL,
    completed_timestamp INTEGER NOT NULL,
    failure_count INTEGER NOT NULL,
    retry_count INTEGER NOT NULL,
    last_failure_time INTEGER NOT NULL,
    stage TEXT NOT NULL,
    qos_desired_count INTEGER NOT NULL,
    probe_only_qos_completed_count INTEGER NOT NULL,
    full_qos_completed_count INTEGER NOT NULL,
    unsuitable_session_count INTEGER NOT NULL,
    unsuitable_reasons_count INTEGER[12],
    undesireable_session_count INTEGER NOT NULL,
    undesirable_reasons_count INTEGER[2],
    join_results INTEGER[20],
    stage_round INTEGER NOT NULL,
    hopper_identifier SMALLINT NOT NULL,
    min_skill_level INTEGER NOT NULL,
    max_skill_level INTEGER NOT NULL,
    party_size INTEGER NOT NULL,
    mixed_skill_party BOOLEAN NOT NULL,
    nat_type TEXT NOT NULL,
    min_average_skill_level INTEGER NOT NULL,
    max_average_skill_level INTEGER NOT NULL,
    average_mu_min FLOAT NOT NULL,
    average_mu_max FLOAT NOT NULL,
    min_average_experience_rating INTEGER NOT NULL,
    max_average_experience_rating INTEGER NOT NULL,
    gamer_zone TEXT NOT NULL,
    gamer_region INTEGER NOT NULL,
    language TEXT NOT NULL,
    connection_threshold_ms INTEGER NOT NULL,
    session_of_quitters BOOLEAN NOT NULL,
    search_preference TEXT NOT NULL,
    query_flags SMALLINT NOT NULL,
    query TEXT NOT NULL,
    FOREIGN KEY (matchmaking_quality_id) REFERENCES halo3.matchmaking_quality(id)
);

CREATE TABLE halo3.matchmaking_session_search_property (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    matchmaking_search_id UUID NOT NULL,
    property TEXT NOT NULL,
    property_type TEXT NOT NULL,
    property_value TEXT NOT NULL,
    FOREIGN KEY (matchmaking_search_id) REFERENCES halo3.matchmaking_session_search(id)
);

CREATE TABLE halo3.matchmaking_session_search_context (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    matchmaking_search_id UUID NOT NULL,
    context_id TEXT NOT NULL,
    context_value TEXT NOT NULL,
    FOREIGN KEY (matchmaking_search_id) REFERENCES halo3.matchmaking_session_search(id)
);